name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "0.34.1"
          rebar3-version: "3"
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: gleam format --check src test
      - run: gleam deps download
      - run: yarn
      - run: yarn test
