name: ci

on:
  push:
    branches:
      - main
  pull_request:

env:
  otp: "27.0"
  gleam: "1.8.0"
  rebar: "3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          gleam-version: ${{ env.gleam }}
          rebar3-version: ${{ env.rebar }}
      - run: gleam format --check src test
      - run: gleam build

  erlang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          gleam-version: ${{ env.gleam }}
          rebar3-version: ${{ env.rebar }}
      - run: gleam test --target erlang

  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 23.x]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          gleam-version: ${{ env.gleam }}
          rebar3-version: ${{ env.rebar }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn
      - run: yarn build
      - run: gleam test --target javascript --runtime nodejs
      - run: node --test ./specs/test_dist.spec.js

  bun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          gleam-version: ${{ env.gleam }}
          rebar3-version: ${{ env.rebar }}
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: yarn build
      - run: gleam test --target javascript --runtime bun
      - run: bun test ./specs/test_dist.spec.js

  deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          gleam-version: ${{ env.gleam }}
          rebar3-version: ${{ env.rebar }}
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x # Run with latest stable Deno.
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn build
      - run: gleam test --target javascript --runtime deno
      - run: deno test ./specs/test_dist.spec.js